# Generated by Django 4.1.5 on 2023-01-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine_app', '0004_alter_movie_list_poster_alter_movie_list_wallpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_list',
            name='poster',
            field=models.ImageField(upload_to='media/posters/'),
        ),
        migrations.AlterField(
            model_name='movie_list',
            name='wallpaper',
            field=models.ImageField(upload_to='media/wallpapers/'),
        ),
    ]
