# Generated by Django 4.1.5 on 2023-02-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine_app', '0005_alter_movie_list_poster_alter_movie_list_wallpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='timeslot_1',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='timeslot_2',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='timeslot_3',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='timeslot_4',
            field=models.TimeField(),
        ),
    ]
