# Generated by Django 4.1.5 on 2023-02-03 09:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cine_app', '0008_alter_book_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='timeslots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot_1', models.CharField(max_length=10)),
                ('timeslot_2', models.TimeField()),
                ('timeslot_3', models.TimeField()),
                ('timeslot_4', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='timeslot_1',
        ),
        migrations.RemoveField(
            model_name='book',
            name='timeslot_2',
        ),
        migrations.RemoveField(
            model_name='book',
            name='timeslot_3',
        ),
        migrations.RemoveField(
            model_name='book',
            name='timeslot_4',
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='book',
            name='time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cine_app.timeslots'),
            preserve_default=False,
        ),
    ]
