# Generated by Django 4.1.5 on 2023-02-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine_app', '0009_timeslots_remove_book_timeslot_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='seat_num',
        ),
        migrations.AddField(
            model_name='book',
            name='seats',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='ticket_date',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
