# Generated by Django 4.1.5 on 2023-02-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine_app', '0010_remove_book_date_remove_book_seat_num_book_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ticket_date',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
