# Generated by Django 4.1.5 on 2023-02-03 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cine_app', '0012_rename_ticket_date_book_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslots',
            name='timeslot_2',
        ),
        migrations.RemoveField(
            model_name='timeslots',
            name='timeslot_3',
        ),
        migrations.RemoveField(
            model_name='timeslots',
            name='timeslot_4',
        ),
    ]
