# Generated by Django 4.1.5 on 2023-02-06 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cine_app', '0016_remove_userprofileinfo_portfolio_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='book2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField(default=1)),
                ('date', models.DateField(default='2023-01-01')),
                ('movie_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine_app.movie_list')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine_app.timeslots')),
            ],
        ),
    ]
