# Generated by Django 4.1.5 on 2023-02-16 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cine_app', '0019_rename_movie_book3_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book3',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
